receivers:
  otlp:
    protocols:
      http:
      grpc:

exporters:
  googlecloud:
    log:
      default_log_name: opentelemetry.io/collector
  logging:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [googlecloud, logging]
